version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web.dev
        user: "${USER_ID}:${GROUP_ID}"
        environment:
            - FLASK_APP=/code/chaostoolbox/helloworld.py
            - FLASK_DEBUG=1
        ports:
            - 8080:8080
        volumes:
            - "./chaostoolbox:/code/chaostoolbox:rw"
            - "./.config/ansible:/etc/ansible:rw"
            - "./.config/ssh:/home/code/.ssh"

