FROM ansible/ansible:ubuntu1604


RUN sudo apt-get update \
    && apt-get install -y --no-install-recommends --fix-missing tcl tk expect \
    && git clone https://github.com/XLab-Tongji/Ansible_Operator.git ~/Ansible_Operator \
    && chmod 777 ~/Ansible_Operator/auto_ssh.sh \
    && rm /etc/ansible/hosts \
    && cp ~/Ansible_Operator/hosts /etc/ansible/hosts \
    && pip install --upgrade pip \
    && pip2 install ansible==2.7.10 \
    && pip2 install flask \
    && pip2 install flask_httpauth \
    && pip2 install requests \
    && pip2 install influxdb \
    && git -C /root/Ansible_Operator pull \
    && chmod 777 ~/Ansible_Operator/run.sh


CMD ["sh", "/root/Ansible_Operator/run.sh"]





