---
- hosts: Lab409-hm
  user: root
  tasks: 
    - name: ssh-key-copy
      authorized_key: user=root key="{{ lookup('file','~/.ssh/id_rsa.pub')}}"
      tags:
        - sshkey
- hosts: Lab409-vm
  user: root
  tasks:
    - name: ssh-key-copy
      authorized_key: user=root key="{{ lookup('file','~/.ssh/id_rsa.pub')}}"
      tags:
        - sshkey
- hosts: Lab409-master
  user: root
  tasks:
    - name: ssh-key-copy
      authorized_key: user=root key="{{ lookup('file','~/.ssh/id_rsa.pub')}}"
      tags:
        - sshkey
- hosts: Lab409-vm-master
  user: root
  tasks:
    - name: ssh-key-copy
      authorized_key: user=serveradmin key="{{ lookup('file','~/.ssh/id_rsa.pub')}}"
      tags:
        - sshkey
